package nxweb

import (
	"bytes"
	"compress/gzip"
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"math/big"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/tkdeng/goutil"
	"github.com/tkdeng/regex"
	"github.com/tkdeng/simplewebserver/cron"
)

// autoTLS will automatically generate a self signed tls certificate
// and auto renew it on a cron job when it expires (assuming a 1 year renewal)
//
// @certPath: file path to store ssl certificates to
// (this will generate a my/path.crt and my/path.key file)
func (app *App) autoTLS(certPath string) (crt string, key string, err error) {
	certPath = regex.Comp(`\.(crt|key)$`).RepLitStr(certPath, "")

	// generate ssl cert if needed
	os.MkdirAll(filepath.Dir(certPath), 0755)
	err = GenRsaKeyIfNeeded(certPath+".crt", certPath+".key")
	if err != nil {
		return "", "", err
	}

	// auto renew ssl cert if expired
	cron.New(24*time.Hour, func() bool {
		err := GenRsaKeyIfNeeded(certPath+".crt", certPath+".key")
		if err != nil {
			fmt.Println(err)
			return false
		}
		return true
	})

	return certPath + ".crt", certPath + ".key", nil
}

// GenRsaKeyIfNeeded auto detects if the certificates generated by
// the GenRsaKey method are either
//   - not synchronized by date modified
//   - are possibly expired (assuming a 1 year renewal)
//
// If it detects this is true, it will automatically regenerate a new certificate
func GenRsaKeyIfNeeded(crtPath string, keyPath string) error {
	crtStat, crtErr := os.Stat(crtPath)
	keyStat, keyErr := os.Stat(keyPath)

	if crtErr != nil || keyErr != nil {
		err := GenRsaKey(crtPath, keyPath)
		if err != nil {
			return err
		}
		return nil
	}

	crtTime := crtStat.ModTime()
	keyTime := keyStat.ModTime()

	// regenerate if cert and key not synced || its been 1 year
	if crtTime.UnixMilli()/60000 != keyTime.UnixMilli()/60000 || time.Now().Year() > crtTime.Year() {
		_, err := goutil.CopyFile(crtPath, crtPath+".old")
		if err != nil {
			os.Remove(crtPath + ".old")
			return err
		}

		_, err = goutil.CopyFile(keyPath, keyPath+".old")
		if err != nil {
			os.Remove(crtPath + ".old")
			os.Remove(keyPath + ".old")
			return err
		}

		err = GenRsaKey(crtPath, keyPath)
		if err != nil {
			if _, e := goutil.CopyFile(crtPath+".old", crtPath); e == nil {
				os.Remove(crtPath + ".old")
			}

			if _, e := goutil.CopyFile(keyPath+".old", keyPath); e == nil {
				os.Remove(keyPath + ".old")
			}

			return err
		}
	}

	return nil
}

// GenRsaKey generates a new ssl certificate and key pair
//   - expires: 3 years
//   - rsa: 4096
//   - x509
//   - sha256
//   - recommended renewal: once a year
func GenRsaKey(crtPath string, keyPath string) error {
	//// 10 years: openssl req -newkey rsa:4096 -x509 -sha256 -days 3650 -nodes -out example.crt -keyout example.key
	// 3 years: openssl req -newkey rsa:4096 -x509 -sha256 -days 1095 -nodes -out example.crt -keyout example.key

	PrintMsg(`warn`, "Generating New SSL Certificate...", 50, false)

	// Generate RSA key
	key, err := rsa.GenerateKey(rand.Reader, 4096)
	if err != nil {
		PrintMsg(`error`, "Error: Failed To Generate SSL Certificate!", 50, true)
		return err
	}

	keyBytes := x509.MarshalPKCS1PrivateKey(key)
	// PEM encoding of private key
	keyPEM := pem.EncodeToMemory(
		&pem.Block{
			Type:  "RSA PRIVATE KEY",
			Bytes: keyBytes,
		},
	)

	notBefore := time.Now()
	notAfter := notBefore.Add(365 * 24 * 3 * time.Hour)

	// Create certificate template
	template := x509.Certificate{
		SerialNumber:          big.NewInt(0),
		Subject:               pkix.Name{CommonName: "localhost"},
		SignatureAlgorithm:    x509.SHA256WithRSA,
		NotBefore:             notBefore,
		NotAfter:              notAfter,
		BasicConstraintsValid: true,
		KeyUsage:              x509.KeyUsageDigitalSignature | x509.KeyUsageKeyAgreement | x509.KeyUsageKeyEncipherment | x509.KeyUsageDataEncipherment,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth, x509.ExtKeyUsageClientAuth},
	}

	// Create certificate using template
	derBytes, err := x509.CreateCertificate(rand.Reader, &template, &template, &key.PublicKey, key)
	if err != nil {
		PrintMsg(`error`, "Error: Failed To Generate SSL Certificate!", 50, true)
		return err
	}

	// pem encoding of certificate
	certPem := pem.EncodeToMemory(
		&pem.Block{
			Type:  "CERTIFICATE",
			Bytes: derBytes,
		},
	)

	// Write key to file
	if err := os.WriteFile(crtPath, certPem, 0600); err != nil {
		PrintMsg(`error`, "Error: Failed To Generate SSL Certificate!", 50, true)
		return err
	}

	// Write cert to file
	if err := os.WriteFile(keyPath, keyPEM, 0600); err != nil {
		PrintMsg(`error`, "Error: Failed To Generate SSL Certificate!", 50, true)
		return err
	}

	PrintMsg(`warn`, "New SSL Certificate Generated!", 50, true)

	return nil
}

// Gzip will compress the given bytes and save them to a gzip file at the specified path
func Gzip(path string, data []byte) error {
	file, err := os.Create(path)
	if err != nil {
		return err
	}
	defer file.Close()

	// NewWriterLevel lets you balance speed vs compression ratio
	// gzip.DefaultCompression is usually the best "set and forget"
	gz := gzip.NewWriter(file)
	defer gz.Close()

	_, err = gz.Write(data)
	return err
}

// Gunzip will decompress a gzip file and return the bytes
func Gunzip(path string) ([]byte, error) {
	file, err := os.Open(path)
	if err != nil {
		return []byte{}, err
	}
	defer file.Close()

	gz, err := gzip.NewReader(file)
	if err != nil {
		return []byte{}, err
	}
	defer gz.Close()

	var buf bytes.Buffer
	if _, err := buf.ReadFrom(gz); err != nil {
		return []byte{}, err
	}

	return buf.Bytes(), nil
}

// CapWords capitalizes the first letter of each word in a string
func capWords(str string) string {
	//bug: for some weird reason, using `^[a-z]` in regex selects every letter instead of just selecting the first leter
	b := regex.Comp(`(\s[a-z])`).RepFunc([]byte(str), func(data func(int) []byte) []byte {
		return bytes.ToUpper(data(1))
	})

	if len(b) != 0 {
		b[0] = bytes.ToUpper([]byte{b[0]})[0]
	}

	return string(b)
}

// EscapeHTML escapes HTML characters and HTML arg quotes
//
// @mode (optional):
//   - "html": escapes html characters
//   - "args": escapes quotes for html args
func EscapeHTML(html []byte, mode ...string) []byte {
	if len(mode) == 0 {
		mode = []string{""}
	}

	switch mode[0] {
	case "html":
		return goutil.HTML.Escape(html)
	case "args":
		return goutil.HTML.EscapeArgs(html)
	default:
		return goutil.HTML.EscapeArgs(goutil.HTML.Escape(html))
	}
}

// PrintMsg prints to console and auto inserts spaces
func PrintMsg(color string, msg string, size int, end bool) {
	if size > len(msg) {
		msg += strings.Repeat(" ", size-len(msg))
	}

	if color == "none" {
		color = "0"
	} else if color == "error" {
		color = "1;31"
	} else if color == "confirm" {
		color = "1;32"
	} else if color == "warn" {
		color = "1;33"
	} else if color == "info" {
		color = "1;34"
	} else if color == "value" {
		color = "1;35"
	}

	if end {
		fmt.Println("\r\x1b[" + color + "m" + msg + "\x1b[0m")
	} else {
		fmt.Print("\r\x1b[" + color + "m" + msg + "\x1b[0m")
	}
}

// ToType attempts to converts an interface{} from the many possible types in golang, to a specific type of your choice
//
// if it fails to convert, it will return a nil/zero value for the appropriate type
func ToType[T goutil.SupportedType](val any) T {
	return goutil.ToType[T](val)
}
